// Mapeo de equipos a sus banderas
export const teamFlags: Record<string, string> = {
  'Argentina': '🇦🇷',
  'Brasil': '🇧🇷',
  'España': '🇪🇸',
  'Alemania': '🇩🇪',
  'Francia': '🇫🇷',
  'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Portugal': '🇵🇹',
  'Italia': '🇮🇹',
  'Holanda': '🇳🇱',
  'Bélgica': '🇧🇪',
  'México': '🇲🇽',
  'Uruguay': '🇺🇾',
  'Colombia': '🇨🇴',
  'Chile': '🇨🇱',
  'Perú': '🇵🇪',
  'Ecuador': '🇪🇨',
  'Estados Unidos': '🇺🇸',
  'Canadá': '🇨🇦',
  'Costa Rica': '🇨🇷',
  'Japón': '🇯🇵',
  'Corea del Sur': '🇰🇷',
  'Australia': '🇦🇺',
  'Marruecos': '🇲🇦',
  'Senegal': '🇸🇳',
  'Túnez': '🇹🇳',
  'Camerún': '🇨🇲',
  'Gales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Escocia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Croacia': '🇭🇷',
  'Serbia': '🇷🇸',
  'Polonia': '🇵🇱',
  'Dinamarca': '🇩🇰',
  'Suiza': '🇨🇭',
  'Suecia': '🇸🇪',
  'Austria': '🇦🇹',
  'República Checa': '🇨🇿',
  'Turquía': '🇹🇷',
  'Ucrania': '🇺🇦',
  'Noruega': '🇳🇴',
}

export function getTeamFlag(teamName: string): string {
  return teamFlags[teamName] || '⚽'
}
