// Mapeo de equipos a código ISO 2 letras para flagcdn.com
export const teamCountryCodes: Record<string, string> = {
  'Argentina': 'ar',
  'Brasil': 'br',
  'España': 'es',
  'Alemania': 'de',
  'Francia': 'fr',
  'Inglaterra': 'gb-eng',
  'Portugal': 'pt',
  'Italia': 'it',
  'Holanda': 'nl',
  'Países Bajos': 'nl',
  'Bélgica': 'be',
  'México': 'mx',
  'Uruguay': 'uy',
  'Colombia': 'co',
  'Chile': 'cl',
  'Perú': 'pe',
  'Ecuador': 'ec',
  'Bolivia': 'bo',
  'Paraguay': 'py',
  'Venezuela': 've',
  'Estados Unidos': 'us',
  'Canadá': 'ca',
  'Costa Rica': 'cr',
  'Panamá': 'pa',
  'Honduras': 'hn',
  'El Salvador': 'sv',
  'Jamaica': 'jm',
  'Trinidad y Tobago': 'tt',
  'Japón': 'jp',
  'Corea del Sur': 'kr',
  'Australia': 'au',
  'Nueva Zelanda': 'nz',
  'Arabia Saudita': 'sa',
  'Irán': 'ir',
  'Qatar': 'qa',
  'Emiratos Árabes': 'ae',
  'Marruecos': 'ma',
  'Senegal': 'sn',
  'Túnez': 'tn',
  'Camerún': 'cm',
  'Ghana': 'gh',
  'Nigeria': 'ng',
  'Egipto': 'eg',
  'Costa de Marfil': 'ci',
  'Mali': 'ml',
  'Gales': 'gb-wls',
  'Escocia': 'gb-sct',
  'Irlanda del Norte': 'gb-nir',
  'Irlanda': 'ie',
  'Croacia': 'hr',
  'Serbia': 'rs',
  'Polonia': 'pl',
  'Dinamarca': 'dk',
  'Suiza': 'ch',
  'Suecia': 'se',
  'Austria': 'at',
  'República Checa': 'cz',
  'Turquía': 'tr',
  'Ucrania': 'ua',
  'Noruega': 'no',
  'Finlandia': 'fi',
  'Hungría': 'hu',
  'Eslovenia': 'si',
  'Eslovaquia': 'sk',
  'Rumania': 'ro',
  'Bulgaria': 'bg',
  'Grecia': 'gr',
  'Albania': 'al',
  'Georgia': 'ge',
  'Rusia': 'ru',
}

// Retorna la URL de la imagen de bandera (flagcdn.com)
export function getTeamFlagUrl(teamName: string, size: 20 | 40 | 80 | 160 = 40): string {
  const code = teamCountryCodes[teamName]
  if (!code) return ''
  return `https://flagcdn.com/w${size}/${code}.png`
}

// Retorna el código ISO del equipo
export function getTeamCode(teamName: string): string | null {
  return teamCountryCodes[teamName] || null
}
