// Mapeo de equipos a código ISO 2 letras para flagcdn.com
export const teamCountryCodes: Record<string, string> = {
  // América del Sur
  'Argentina': 'ar',
  'Brasil': 'br',
  'Uruguay': 'uy',
  'Colombia': 'co',
  'Chile': 'cl',
  'Perú': 'pe',
  'Ecuador': 'ec',
  'Bolivia': 'bo',
  'Paraguay': 'py',
  'Venezuela': 've',
  // América del Norte / Centro
  'México': 'mx',
  'Estados Unidos': 'us',
  'Canadá': 'ca',
  'Costa Rica': 'cr',
  'Panamá': 'pa',
  'Honduras': 'hn',
  'El Salvador': 'sv',
  'Jamaica': 'jm',
  'Trinidad y Tobago': 'tt',
  'Haití': 'ht',
  // Europa
  'España': 'es',
  'Alemania': 'de',
  'Francia': 'fr',
  'Inglaterra': 'gb-eng',
  'Portugal': 'pt',
  'Italia': 'it',
  'Holanda': 'nl',
  'Países Bajos': 'nl',
  'Bélgica': 'be',
  'Croacia': 'hr',
  'Serbia': 'rs',
  'Polonia': 'pl',
  'Dinamarca': 'dk',
  'Suiza': 'ch',
  'Suecia': 'se',
  'Austria': 'at',
  'República Checa': 'cz',
  'Turquía': 'tr',
  'Ucrania': 'ua',
  'Noruega': 'no',
  'Finlandia': 'fi',
  'Hungría': 'hu',
  'Eslovenia': 'si',
  'Eslovaquia': 'sk',
  'Rumania': 'ro',
  'Bulgaria': 'bg',
  'Grecia': 'gr',
  'Albania': 'al',
  'Georgia': 'ge',
  'Rusia': 'ru',
  'Escocia': 'gb-sct',
  'Gales': 'gb-wls',
  'Irlanda del Norte': 'gb-nir',
  'Irlanda': 'ie',
  'Bosnia y Herzegovina': 'ba',
  // Asia / Oceanía
  'Japón': 'jp',
  'Corea del Sur': 'kr',
  'Australia': 'au',
  'Nueva Zelanda': 'nz',
  'Arabia Saudita': 'sa',
  'Irán': 'ir',
  'Qatar': 'qa',
  'Emiratos Árabes': 'ae',
  'Irak': 'iq',
  'Jordania': 'jo',
  'Uzbekistán': 'uz',
  // África
  'Marruecos': 'ma',
  'Senegal': 'sn',
  'Túnez': 'tn',
  'Camerún': 'cm',
  'Ghana': 'gh',
  'Nigeria': 'ng',
  'Egipto': 'eg',
  'Costa de Marfil': 'ci',
  'Mali': 'ml',
  'Sudáfrica': 'za',
  'Argelia': 'dz',
  'DR Congo': 'cd',
  'República Democrática del Congo': 'cd',
  // Caribe / Insulares
  'Curaçao': 'cw',
  'Cabo Verde': 'cv',
  'Cuba': 'cu',
  'Guatemala': 'gt',
  'Surinam': 'sr',
  'Guyana': 'gy',
  'Nicaragua': 'ni',
  // Europa adicional (UEFA Nations League)
  'Rumanía': 'ro',
  'Islandia': 'is',
  'Montenegro': 'me',
  'Kazajistán': 'kz',
  'Azerbaiyán': 'az',
  'Kosovo': 'xk',
  'Armenia': 'am',
  'Bielorrusia': 'by',
  'Macedonia del Norte': 'mk',
  'Lituania': 'lt',
  'Letonia': 'lv',
  'Estonia': 'ee',
  'Andorra': 'ad',
  'Gibraltar': 'gi',
  'Liechtenstein': 'li',
  'Luxemburgo': 'lu',
  'Malta': 'mt',
  'Moldavia': 'md',
  'San Marino': 'sm',

  // ── English name aliases (ESPN import stores English country names) ──
  // Europe
  'England': 'gb-eng',
  'France': 'fr',
  'Germany': 'de',
  'Spain': 'es',
  'Italy': 'it',
  'Netherlands': 'nl',
  'Belgium': 'be',
  'Croatia': 'hr',
  'Poland': 'pl',
  'Denmark': 'dk',
  'Switzerland': 'ch',
  'Sweden': 'se',
  'Czechia': 'cz',
  'Czech Republic': 'cz',
  'Turkey': 'tr',
  'Türkiye': 'tr',
  'Ukraine': 'ua',
  'Norway': 'no',
  'Finland': 'fi',
  'Hungary': 'hu',
  'Slovenia': 'si',
  'Slovakia': 'sk',
  'Romania': 'ro',
  'Greece': 'gr',
  'Scotland': 'gb-sct',
  'Wales': 'gb-wls',
  'Republic of Ireland': 'ie',
  'Northern Ireland': 'gb-nir',
  'Bosnia-Herzegovina': 'ba',
  'Bosnia & Herzegovina': 'ba',
  'Iceland': 'is',
  'Kazakhstan': 'kz',
  'Azerbaijan': 'az',
  'Belarus': 'by',
  'North Macedonia': 'mk',
  'Latvia': 'lv',
  'Luxembourg': 'lu',
  'Moldova': 'md',
  // Americas
  'Brazil': 'br',
  'Peru': 'pe',
  'United States': 'us',
  'USA': 'us',
  'Mexico': 'mx',
  'Canada': 'ca',
  'Panama': 'pa',
  'Trinidad & Tobago': 'tt',
  'Haiti': 'ht',
  'Curacao': 'cw',
  'Suriname': 'sr',
  // Asia / Africa / Oceania
  'Japan': 'jp',
  'South Korea': 'kr',
  'Korea Republic': 'kr',
  'New Zealand': 'nz',
  'Saudi Arabia': 'sa',
  'Iran': 'ir',
  'Iraq': 'iq',
  'Jordan': 'jo',
  'Uzbekistan': 'uz',
  'Morocco': 'ma',
  'Tunisia': 'tn',
  'Egypt': 'eg',
  'Ivory Coast': 'ci',
  "Côte d'Ivoire": 'ci',
  'South Africa': 'za',
  'Algeria': 'dz',
  'Cape Verde': 'cv',
}

// Retorna la URL de la imagen de bandera (flagcdn.com)
export function getTeamFlagUrl(teamName: string, size: 20 | 40 | 80 | 160 = 40): string {
  const code = teamCountryCodes[teamName]
  if (!code) return ''
  return `https://flagcdn.com/w${size}/${code}.png`
}

// Retorna el código ISO del equipo
export function getTeamCode(teamName: string): string | null {
  return teamCountryCodes[teamName] || null
}
